### ISSUE TITLE
Météo France relies on web scraping

### ISSUE THREAD

**Issue by Quentame** [victorcerutti/meteofrance-py#12]
Following home-assistant/home-assistant#31925

This library uses web scraping over Beautiful Soup in order to get data, this should be removed to use an API instead.

**Comment by oncleben31** [comment]
There is a private API used for mobile app (see #8).
But I think we need further investigations to understand how the identification and the API key generation work.
This is a call for volunteers :smile: 
Open question: if we find a solution with the API, do we overwrite the old architecture of this module or do we keep the current one and ceate a new python package?

**Comment by Quentame** [comment]
I think we can override this library and make a major release version.

I can help, how are the states of the research about the private API ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by oncleben31** [comment]
I think I'm the one who starts in the #8 issue. I didn't find any related post with Google. And others Home Automation systems rely on the web scraping too.
I didn't catch the API exchange during the first launch of the app where I expect to have a process to get a user ID and a API key.

**Comment by oncleben31** [comment]
Won't be fixed in this repo. A new Python module have been developed and is used now by HA core: https://github.com/hacf-fr/meteofrance-api
